name: smartaccess_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  lottie: ^3.1.0
  fluttertoast: ^8.2.5
  camera: ^0.10.6
  cloudinary_flutter: ^1.0.0
  cloudinary_url_gen: ^1.0.0
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  logging: ^1.2.0
  http: any
  provider: ^6.1.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/lottie/
    - assets/images/
    - assets/models/
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Bold.ttf